### ISSUE TITLE
Status on Cosy parameters marked as Unavailable

### ISSUE THREAD

**Issue by Odyzak** [BottlecapDave/HomeAssistant-OctopusEnergy#1304]
### Describe the bug

All parameters from Cosy hub are marked as unavailable, including temp sensors and all other readouts, despite the values being available through Octopus

### Reproduction steps

Unknown, happens periodically. Not sure if it is due to water/heating modes being set to off for a period of time

### Expected behaviour

Values reported and available

### Tariff Code

E-1R-COSY-22-12-08-

### Integration Version

15.0.0

### Home Assistant Version

15.1

### Fresh Install?

Not specified

### Home Assistant Logs

This error originated from a custom integration.

Logger: custom_components.octopus_energy.coordinators.heat_pump_configuration_and_status
Source: helpers/update_coordinator.py:380
integration: Octopus Energy (documentation, issues)
First occurred: 8:57:12 PM (8 occurrences)
Last logged: 9:04:39 PM

Unexpected error fetching heat_pump_A-A644A488 data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/coordinators/heat_pump_configuration_and_status.py", line 106, in async_update_heat_pump_data
    hass.data[DOMAIN][account_id][key] = await async_refresh_heat_pump_configuration_and_status(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/config/custom_components/octopus_energy/coordinators/heat_pump_configuration_and_status.py", line 56, in async_refresh_heat_pump_configuration_and_status
    status_and_configuration = await client.async_get_heat_pump_configuration_and_status(account_id, euid)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/api_client/__init__.py", line 903, in async_get_heat_pump_configuration_and_status
    return HeatPumpResponse.parse_obj(response["data"])
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pydantic/main.py", line 1222, in parse_obj
    return cls.model_validate(obj)
           ~~~~~~~~~~~~~~~~~~^^^^^
  File "/usr/local/lib/python3.13/site-packages/pydantic/main.py", line 627, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        obj, strict=strict, from_attributes=from_attributes, context=context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
pydantic_core._pydantic_core.ValidationError: 1 validation error for HeatPumpResponse
octoHeatPumpControllerConfiguration.heatPump.faultCodes
  Field required [type=missing, input_value={'serialNumber': '0000000...': 'DEGREES_CELSIUS'}}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing

### Confirmation

- [x] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [x] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by Odyzak** [comment]
Not really sure if this is the same isse as before Dave, I'm useless with code haha.

Had it all working as normal for a few hours today then died off again with this error. Can't get it back on with running any of the pump so maybe not due to them being set to off? Is this all on Octopus' API side?

Thanks for the help in advance

**Comment by BottlecapDave** [comment]
Nope this one is on me. I removed the request for some data as it wasn't being used and it was causing issues, however I forgot to update some supporting code. I'll try and get a fix out later today

**Comment by BottlecapDave** [comment]
This should hopefully be fixed as part of v15.0.1. Sorry for the issues.

**Comment by Odyzak** [comment]
Thanks so much Dave, all seems to be functional. I'll be sure to throw you some support as thanks :)

**Comment by jimo2024** [comment]
The update to 15.0.1 has resolved most of this for me. However Live COP and Lifetime SCOP remain unavailable for me...

**Comment by MattSharp** [comment]
I still have a value for lifetime scop, but live cop has stopped pulling through data

**Comment by jimo2024** [comment]
I've seen that octopus have removed Live COP from their app. Maybe that's something to do with it? I might add a helper that calculates it for me instead.

**Comment by BottlecapDave** [comment]
If certain data is missing, then this will most likely be due to the OE API not reporting the data so is out of my control. You'll need to contact OE if this data is not being reported. If OE have removed it from the app, it suggests it's either not working consistently or it's about to be removed from the API.

**Comment by MattSharp** [comment]
> I’m missing the live outdoor temperature sensor data (now showing as unknown)

My outdoor temp flatlined at 8:30 this morning, as Dave said earlier though I imagine this is on Octopus just making API changes, which is a shame as I use the outdoor temp to display on my Aqara W100 displays so I guess I need a new outdoor temp sensor!

**Comment by mat5968** [comment]
@MattSharp , @jackyoung1 , @BottlecapDave  - My Live Outdoor temp is still updating and working as I'd expect.  I am on 15.0.1.  (I have lost Live COP, but this is answered by above comments).

**Comment by MattSharp** [comment]
> [@MattSharp](https://github.com/MattSharp) , [@jackyoung1](https://github.com/jackyoung1) , [@BottlecapDave](https://github.com/BottlecapDave) - My Live Outdoor temp is still updating and working as I'd expect. I am on 15.0.1. (I have lost Live COP, but this is answered by above comments).

My outdoor temp returned at 11:50, so looks like a glitch on that one perhaps

**Comment by BottlecapDave** [comment]
Is this still an issue for everyone or can this issue be closed off?

**Comment by jackyoung1** [comment]
My outdoor temp, lifetime cop and lifetime energy input and outputs are still showing as unknown

**Comment by BottlecapDave** [comment]
Are you able to follow the faq and retrieve the diagnostic data and copy the results here? It should show the raw value for these values

**Comment by jackyoung1** [comment]
Sure!

[config_entry-octopus_energy-382dd6fb429ca62bcee141391e4bc14e.json](https://github.com/user-attachments/files/20126424/config_entry-octopus_energy-382dd6fb429ca62bcee141391e4bc14e.json)

**Comment by Redding43** [comment]
I think my lifetime Scop has flatlined and Live Cop has stopped working and stuck at zero

**Comment by irata-coder** [comment]
I think there might be a typo that has crept into in sensor_live_cop.py

`Logger: homeassistant
Source: custom_components/octopus_energy/heat_pump/sensor_live_cop.py:79
integration: Octopus Energy ([documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy), [issues](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues))
First occurred: 9 May 2025 at 21:09:16 (2349 occurrences)
Last logged: 15:23:20

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 479, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 178, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/config/custom_components/octopus_energy/heat_pump/sensor_live_cop.py", line 79, in _handle_coordinator_update
    self._state = float(result.data.octoHeatPumpLivePerformance.coefficientOfPerformance) if result.data.octoHeatPumpLivePerformance.coefficientOfPerformanc is not None else None
                                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pydantic/main.py", line 994, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'OctoHeatPumpLivePerformance' object has no attribute 'coefficientOfPerformanc'. Did you mean: 'coefficientOfPerformance'?`

**Comment by BottlecapDave** [comment]
Sorry I thought I'd responded to this :(  The data @jackyoung1 provided showed data coming through correctly, but that the sensors were not updating. When I changed my local mocked data to be identical to theirs, I spotted this error. I believe this error is what's causing other sensors from not updating. I've fixed the issue locally, and just testing some other fixes and hope to do an update today or tomorrow.

**Comment by BottlecapDave** [comment]
This should hopefully be fixed as part of [v15.0.2](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v15.0.2)

**Comment by jackyoung1** [comment]
Upgraded but still showing as unknown, diagnostics showing the value as present:  "outdoorTemperature": {            "value": "19.700",            "unit": "DEGREES_CELSIUS"          },          "readAt": "2025-05-12T18:53:51.764000+01:00"Sent from my iPhoneOn 12 May 2025, at 18:44, David Kendall ***@***.***> wrote:﻿
BottlecapDave left a comment (BottlecapDave/HomeAssistant-OctopusEnergy#1304)
This should hopefully be fixed as part of v15.0.2

**Comment by BottlecapDave** [comment]
I'm not sure why it's not coming through as I've tested with your data and everything seems to be coming through fine. Do you have any errors in your logs? Can you supply your diagnostic data again?

**Comment by irata-coder** [comment]
For me, it's working fine now and all the sensor values are now populated.  Albeit I had fixed it locally before, but updating to 15.0.2 works.

**Comment by jackyoung1** [comment]
Sure

[config_entry-octopus_energy-382dd6fb429ca62bcee141391e4bc14e.json](https://github.com/user-attachments/files/20184682/config_entry-octopus_energy-382dd6fb429ca62bcee141391e4bc14e.json)

**Comment by BottlecapDave** [comment]
@jackyoung1 Your diagnostic data suggests you're still using v15.0.1 (line 116 of the file). This suggests it's either not downloaded properly, or you have not restarted your HA instance to apply the update.

**Comment by BottlecapDave** [comment]
Thanks for letting me know. I'll close this issue as the orignal issue and the tangent issue has been resolved
