### ISSUE TITLE
Current rate state appears static

### ISSUE THREAD

**Issue by apbarratt** [BottlecapDave/HomeAssistant-OctopusEnergy#318]
### Describe the bug

I've noticed recently that my Energy dashboard did not seem to be reflecting my nighttime electric rates.  Average platform sensors that are supposed to be showing the minimum and maximum rates for the day also were not adjusting.

As such, I've just inspected the current rate entity to find that it is reflecting the correct rate for my daytime energy (rounded as expected) but when looking at the history chart, I can see this is not adjusting during my Octopus Go rate between 00:30 and 04:30.  However, I can see the different rates shown correctly in the Rates attribute of the entity.

I'm afraid that my export and gas tariffs are static so I cannot provide details of whether these devices are similarly afflicted.

In the screenshot, you can see my rate should be around 0.3 during the day and the state reflects this, however the rates attribute shows it should be around 0.9 during the night, but this is not reflected in the history chart, which shows that it has remained at a constant 0.3.
![Screenshot 2023-07-20 at 13 55 20](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/642320/3f215044-e10a-45b3-9c78-903d3d077e6f)
Please forgive the nasty censor block, I wasn't sure if my mpan or serial number were something I needed to protect or not so figured I'd play it safe.

### Reproduction steps

With an Octopus (i'm not sure if more complex tariffs like Agile are affected), open the current rate entity.
Open the attributes to view the rate changes.
Observe that the history chart does not reflect these rate changes.

### Expected behaviour

The main state of the entity should adjust throughout the day as the rates changes, allowing the Energy Dashboard to give decent estimates of energy costs.

### Tariff Code

E-1R-GO-VAR-22-10-14-N

### Integration Version

7.5.1

### Home Assistant Version

2023.7.2

### Fresh Install?

Not specified

### Home Assistant Logs

Please direct me to any that may be useful.

**Comment by BottlecapDave** [comment]
Thanks for raising the issue and sorry you're not having a good time at the moment with the integration. I think the issue is slightly related to why the saving sensors were going weird. I've made some changes which I'll be testing overnight, and if successful I'll release over the weekend.

**Comment by BottlecapDave** [comment]
I've just released a new update (https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v7.5.2) which should fix this issue, unless there's something more sinister going on.

**Comment by jasonwfrancis1** [comment]
I’m seeing the same thing. I’m on intelligent and the rate did not change at 11:30 as expected. I hit reload on the integration and it did update.

**Comment by BottlecapDave** [comment]
Very interesting. These rate sensors are very basic. Can you follow the [faq](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/faq.md#how-do-i-increase-the-logs-for-the-integration) to increase your logs (I'll need a couple of hours worth of logs) and paste the results here please?

**Comment by jasonwfrancis1** [comment]
Sure I’ll do that today. Checked this morning and the sensor still showed the cheap rate at 7:30 when it ended at 5:30, clicked reload on the integration and it switched rate.

**Comment by apbarratt** [comment]
<img width="993" alt="Screenshot 2023-08-10 at 10 10 16" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/642320/d1fc1867-9e41-4cb9-b1fc-22dd26d41276">
Hmmm, it seems to be working for me properly these days.  Curiously my min/max statistic thingy to give me entities with on/off-peak isn't working though, but that's a problem for me to figure out rather than you.

**Comment by jasonwfrancis1** [comment]
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/6323379/929e81b6-d495-417b-b039-2504a328e668)
Heres mine, ill add my logs below. But youll see i had to reload the integration at 23:35 and then again at 7:25 it should have been 11:30-5:30
________________________________________
Heres all i could fine in my logs relating to the integration:
2023-08-10 12:28:47.674 WARNING (MainThread) [custom_components.octopus_energy.coordinators.saving_sessions] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:47.675 WARNING (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:47.677 WARNING (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:47.677 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.octopus_energy_electricity_22l4466687_2700005559008_current_rate exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2023-08-10 12:28:47.678 WARNING (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:47.680 ERROR (MainThread) [homeassistant.components.sensor] octopus_energy: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
await self.async_update()
File "/config/custom_components/octopus_energy/electricity/standing_charge.py", line 68, in async_update
standard_charge_result = self.coordinator.data[self._mpan] if self.coordinator.data is not None and self._mpan in self.coordinator.data else None
^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'
2023-08-10 12:28:47.684 ERROR (MainThread) [homeassistant.components.sensor] octopus_energy: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
await self.async_update()
File "/config/custom_components/octopus_energy/gas/standing_charge.py", line 74, in async_update
standard_charge_result = self.coordinator.data[self._mprn] if self.coordinator.data is not None and self._mprn in self.coordinator.data else None
^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'
2023-08-10 12:28:47.686 WARNING (MainThread) [custom_components.octopus_energy.coordinators.saving_sessions] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:47.697 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.octopus_energy_gas_e6s13050402361_7746671805_current_rate exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2023-08-10 12:28:48.126 WARNING (MainThread) [custom_components.octopus_energy.coordinators.intelligent_settings] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:48.148 WARNING (MainThread) [custom_components.octopus_energy.coordinators.intelligent_settings] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:48.150 WARNING (MainThread) [custom_components.octopus_energy.coordinators.intelligent_settings] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:48.151 WARNING (MainThread) [custom_components.octopus_energy.coordinators.intelligent_dispatches] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:48.187 WARNING (MainThread) [custom_components.octopus_energy.coordinators.intelligent_dispatches] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:51.830 WARNING (MainThread) [custom_components.octopus_energy.coordinators.saving_sessions] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:51.831 WARNING (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:51.832 WARNING (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:51.832 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.octopus_energy_electricity_22l4466687_2700005559008_current_rate exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2023-08-10 12:28:51.833 WARNING (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:51.834 ERROR (MainThread) [homeassistant.components.sensor] octopus_energy: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
await self.async_update()
File "/config/custom_components/octopus_energy/electricity/standing_charge.py", line 68, in async_update
standard_charge_result = self.coordinator.data[self._mpan] if self.coordinator.data is not None and self._mpan in self.coordinator.data else None
^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'
2023-08-10 12:28:51.837 ERROR (MainThread) [homeassistant.components.sensor] octopus_energy: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
await self.async_update()
File "/config/custom_components/octopus_energy/gas/standing_charge.py", line 74, in async_update
standard_charge_result = self.coordinator.data[self._mprn] if self.coordinator.data is not None and self._mprn in self.coordinator.data else None
^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'
2023-08-10 12:28:51.840 WARNING (MainThread) [custom_components.octopus_energy.coordinators.saving_sessions] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:51.846 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.octopus_energy_gas_e6s13050402361_7746671805_current_rate exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2023-08-10 12:28:52.559 WARNING (MainThread) [custom_components.octopus_energy.coordinators.intelligent_settings] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:52.564 WARNING (MainThread) [custom_components.octopus_energy.coordinators.intelligent_dispatches] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:52.615 WARNING (MainThread) [custom_components.octopus_energy.coordinators.intelligent_settings] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:52.616 WARNING (MainThread) [custom_components.octopus_energy.coordinators.intelligent_dispatches] Debouncer call ignored as shutdown has been requested.
2023-08-10 12:28:52.642 WARNING (MainThread) [custom_components.octopus_energy.coordinators.intelligent_settings] Debouncer call ignored as shutdown has been requested.

**Comment by jasonwfrancis1** [comment]
I have had debug logging running over night. I had to reload the integration at 11:35 as the rate did not update. This morning the rate did not update again, and when I reloaded the integration all of the rate sensors were set to "ünknown". Attached are the logs.
[home-assistant_octopus_energy_2023-08-11T11-21-36.191Z.log](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/files/12320947/home-assistant_octopus_energy_2023-08-11T11-21-36.191Z.log)
[home-assistant.log](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/files/12320948/home-assistant.log)

**Comment by jasonwfrancis1** [comment]
I think I might have found the issue, the sensor for current rate in the statistics screen had a fix me button because it said the type needed to update from “” to “GBP/kWh”, I applied the fix. I’ll see if it updates tonight.

**Comment by jasonwfrancis1** [comment]
I can confirm this was the problem, after doing the fix in statistics the entities are now updating automatically.

**Comment by BottlecapDave** [comment]
Can anyone confirm if this is still an issue with the latest release?

**Comment by apbarratt** [comment]
> Can anyone confirm if this is still an issue with the latest release?

Sorry! I kept meaning to respond to this and kept forgetting, just remembered now I'm seeing an update in my feed.

My current rate sensor seems to now update as I would expect on my Octopus Go tarrif, so that seem to be fixed.  And the little min max statistics sensors I created for Peak and Off-Peak rates seem to be working as a result too :)
<img src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/642320/e3fe2d33-0583-4de4-9cf8-293b056315dc">

I'll let you know if this should change at all after your update too :)

**Comment by widgetwhite** [comment]
I appear to have the same/similar issue. Updated to the latest version of the integration and the current price appears permanently stuck 😢

**Comment by BottlecapDave** [comment]
@widgetwhite Can you please follow the [faq](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/faq.md#how-do-i-increase-the-logs-for-the-integration) and paste the results of the logs here.

**Comment by BottlecapDave** [comment]
The latest release (v8.4.0) will hopefully make this more reliable. Closing due to lack of information.
