### ISSUE TITLE
Device targets don't work

### ISSUE THREAD

**Issue by cspiby** [BottlecapDave/HomeAssistant-OctopusEnergy#76]
I've set this up via HACS, the data appears to be there  as I can see the prices under the attributes but the device targets don't have any data under them so they never trigger, this is what I see under HA states.

**Comment by cspiby** [comment]
![Screenshot_20221022-100742_Chrome](https://user-images.githubusercontent.com/29413212/197331395-09570f97-2ae7-43d8-bdc7-3f8f24dcbe3b.jpg)

**Comment by BottlecapDave** [comment]
Sorry to hear that no times are coming through as part of your target sensor. Do you have any errors in your Home Assistant logs? What tariff are you on?

**Comment by cspiby** [comment]
I can't see any errors in my logs related to your integration, maybe if I was able to turn on verbose logging for your integration it may shed some light? Is that possible?

This is my the cost data is presented, I'm on Octopus Agile

![Screenshot_20221022-184617_Home Assistant](https://user-images.githubusercontent.com/29413212/197355273-ae6ba7d3-bf2f-45a7-9a8c-d5b253c1acaf.jpg)

**Comment by BottlecapDave** [comment]
You can set your log levels as per the instructions at https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy#i-have-sensors-that-are-missing

**Comment by BottlecapDave** [comment]
Also does the history of the sensor ever say it came on? The time at which you posted the issue, it might have hit the small window where there wasn't enough time available within your specified target window and it hadn't started looking at the following days window.

**Comment by cspiby** [comment]
The sensor hasn't been 'on' since setting it up, I would have thought it would have found a 30 minute cheap period in the last day.

I'll enable debug and get back to you.

**Comment by cspiby** [comment]
this is all the logs show

`2022-10-22 21:57:15.002 DEBUG (MainThread) [custom_components.octopus_energy] Finished fetching rates data in 0.000 seconds (success: True)
2022-10-22 21:57:15.003 INFO (MainThread) [custom_components.octopus_energy.binary_sensor] Updating OctopusEnergyTargetRate dishwasher
2022-10-22 21:57:15.005 INFO (MainThread) [custom_components.octopus_energy.binary_sensor] Updating OctopusEnergyTargetRate washing_machine
2022-10-22 21:57:15.007 INFO (MainThread) [custom_components.octopus_energy.binary_sensor] Updating OctopusEnergyTargetRate testing
2022-10-22 21:57:57.002 DEBUG (MainThread) [custom_components.octopus_energy.sensor] Finished fetching rates data in 0.000 seconds (success: True)
2022-10-22 21:57:57.004 DEBUG (MainThread) [custom_components.octopus_energy.sensor] Finished fetching rates data in 0.000 seconds (success: True)
2022-10-22 21:57:57.006 DEBUG (MainThread) [custom_components.octopus_energy.sensor] Finished fetching rates data in 0.000 seconds (success: True)
2022-10-22 21:58:15.002 DEBUG (MainThread) [custom_components.octopus_energy] Finished fetching rates data in 0.000 seconds (success: True)
2022-10-22 21:58:15.003 INFO (MainThread) [custom_components.octopus_energy.binary_sensor] Updating OctopusEnergyTargetRate dishwasher
2022-10-22 21:58:15.005 INFO (MainThread) [custom_components.octopus_energy.binary_sensor] Updating OctopusEnergyTargetRate washing_machine
2022-10-22 21:58:15.008 INFO (MainThread) [custom_components.octopus_energy.binary_sensor] Updating OctopusEnergyTargetRate testing
2022-10-22 21:58:57.002 DEBUG (MainThread) [custom_components.octopus_energy.sensor] Finished fetching rates data in 0.000 seconds (success: True)
2022-10-22 21:58:57.005 DEBUG (MainThread) [custom_components.octopus_energy.sensor] Finished fetching rates data in 0.000 seconds (success: True)
2022-10-22 21:58:57.007 DEBUG (MainThread) [custom_components.octopus_energy.sensor] Finished fetching rates data in 0.000 seconds (success: True)
2022-10-22 21:59:15.002 DEBUG (MainThread) [custom_components.octopus_energy] Finished fetching rates data in 0.000 seconds (success: True)
2022-10-22 21:59:15.004 INFO (MainThread) [custom_components.octopus_energy.binary_sensor] Updating OctopusEnergyTargetRate dishwasher
2022-10-22 21:59:15.005 INFO (MainThread) [custom_components.octopus_energy.binary_sensor] Updating OctopusEnergyTargetRate washing_machine
2022-10-22 21:59:15.008 INFO (MainThread) [custom_components.octopus_energy.binary_sensor] Updating OctopusEnergyTargetRate testing
2022-10-22 21:59:57.002 DEBUG (MainThread) [custom_components.octopus_energy.sensor] Finished fetching rates data in 0.000 seconds (success: True)
2022-10-22 21:59:57.005 DEBUG (MainThread) [custom_components.octopus_energy.sensor] Finished fetching rates data in 0.000 seconds (success: True)
2022-10-22 21:59:57.010 DEBUG (MainThread) [custom_components.octopus_energy.sensor] Finished fetching rates data in 0.001 seconds (success: True)`

**Comment by cspiby** [comment]
Hi, have you any more ideas, none of the created sensors are triggering and there has definitely been cheap periods over the last few days...

![Screenshot 2022-10-26 160723](https://user-images.githubusercontent.com/29413212/198064081-a21319e4-730e-4e6e-a0ed-96ef8c352267.png)

**Comment by BottlecapDave** [comment]
If I'm honest I'm not too sure why you're seeing this. All of the internal testing should have the sensor coming on. 
I have also created a new release (v4.6.3) with some additional logging to try and get some more insight. Am I correct in assuming you only have the one meter, and if not that the target rate has been assigned to the correct meter?

**Comment by cspiby** [comment]
I have an export meter too but I'm definately choosing the correct one (mpan), I'll update to the newest and hopefully it will shed some light on what's happening!

**Comment by cspiby** [comment]
Think there is an error in the latest build as the rates aren't even pulling through now.

`Error while setting up octopus_energy platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/octopus_energy/sensor.py", line 95, in async_setup_entry
    await async_setup_default_sensors(hass, entry, async_add_entities)
  File "/config/custom_components/octopus_energy/sensor.py", line 111, in async_setup_default_sensors
    await rate_coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in async_config_entry_first_refresh
    await self._async_refresh(log_failures=False, raise_on_auth_failed=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 348, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 211, in state
    if (is_on := self.is_on) is None:
  File "/config/custom_components/octopus_energy/binary_sensor.py", line 125, in is_on
    _LOGGER.debug(f'{len(all_rates)} rate periods found for meter {self._config[CONFIG_TARGET_MPAN]}')
TypeError: object of type 'NoneType' has no len()`

**Comment by cspiby** [comment]
The new version isn't actually creating the sensors now, this is the error in the log

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 777, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 211, in state
    if (is_on := self.is_on) is None:
  File "/config/custom_components/octopus_energy/binary_sensor.py", line 125, in is_on
    _LOGGER.debug(f'{len(all_rates)} rate periods found for meter {self._config[CONFIG_TARGET_MPAN]}')
TypeError: object of type 'NoneType' has no len()`

**Comment by BottlecapDave** [comment]
🤦 Sorry about that. I've released a new version which will hopefully fix this issue

**Comment by cspiby** [comment]
It's not producing errors in the log now but it's not producing much else either.

**Comment by BottlecapDave** [comment]
That is very odd. I've setup a target sensor similar to you with log level set to `debug` and the following is an example of the output I would expect (I'm on a fixed rate)

```
2022-10-29 14:35:39.951 DEBUG (MainThread) [custom_components.octopus_energy.binary_sensor] Updating OctopusEnergyTargetRate dishwasher
2022-10-29 14:35:39.951 DEBUG (MainThread) [custom_components.octopus_energy.binary_sensor] 0 rate periods found for meter XXX
2022-10-29 14:35:39.952 DEBUG (MainThread) [custom_components.octopus_energy.target_sensor_utils] Finding rates between 2022-10-29 13:35:39.951884+00:00 and 2022-10-29 21:00:00+00:00
2022-10-29 14:35:39.952 DEBUG (MainThread) [custom_components.octopus_energy.target_sensor_utils] 0 applicable rates found
...
2022-10-29 14:35:45.856 DEBUG (MainThread) [custom_components.octopus_energy.binary_sensor] Updating OctopusEnergyTargetRate dishwasher
2022-10-29 14:35:45.856 DEBUG (MainThread) [custom_components.octopus_energy.binary_sensor] 98 rate periods found for meter XXX
2022-10-29 14:35:45.857 DEBUG (MainThread) [custom_components.octopus_energy.target_sensor_utils] Finding rates between 2022-10-29 13:35:45.856910+00:00 and 2022-10-29 21:00:00+00:00
2022-10-29 14:35:45.857 DEBUG (MainThread) [custom_components.octopus_energy.target_sensor_utils] 14 applicable rates found
2022-10-29 14:35:45.857 DEBUG (MainThread) [custom_components.octopus_energy.target_sensor_utils] Total rates for current block 20.874. Total rates for best block 20.874
2022-10-29 14:35:45.857 DEBUG (MainThread) [custom_components.octopus_energy.target_sensor_utils] Total rates for current block 20.874. Total rates for best block 20.874
2022-10-29 14:35:45.857 DEBUG (MainThread) [custom_components.octopus_energy.target_sensor_utils] Total rates for current block 20.874. Total rates for best block 20.874
2022-10-29 14:35:45.857 DEBUG (MainThread) [custom_components.octopus_energy.target_sensor_utils] Total rates for current block 20.874. Total rates for best block 20.874
2022-10-29 14:35:45.857 DEBUG (MainThread) [custom_components.octopus_energy.target_sensor_utils] Total rates for current block 20.874. Total rates for best block 20.874
2022-10-29 14:35:45.857 DEBUG (MainThread) [custom_components.octopus_energy.target_sensor_utils] Total rates for current block 20.874. Total rates for best block 20.874
2022-10-29 14:35:45.858 DEBUG (MainThread) [custom_components.octopus_energy.target_sensor_utils] Total rates for current block 20.874. Total rates for best block 20.874
2022-10-29 14:35:45.858 DEBUG (MainThread) [custom_components.octopus_energy.target_sensor_utils] Total rates for current block 20.874. Total rates for best block 20.874
2022-10-29 14:35:45.858 DEBUG (MainThread) [custom_components.octopus_energy.target_sensor_utils] Total rates for current block 20.874. Total rates for best block 20.874
2022-10-29 14:35:45.858 DEBUG (MainThread) [custom_components.octopus_energy.target_sensor_utils] Total rates for current block 20.874. Total rates for best block 20.874
2022-10-29 14:35:45.858 DEBUG (MainThread) [custom_components.octopus_energy.target_sensor_utils] Total rates for current block 20.874. Total rates for best block 20.874
2022-10-29 14:35:45.858 DEBUG (MainThread) [custom_components.octopus_energy.target_sensor_utils] Total rates for current block 20.874. Total rates for best block 20.874
2022-10-29 14:35:45.858 DEBUG (MainThread) [custom_components.octopus_energy.target_sensor_utils] Total rates for current block 20.874. Total rates for best block 20.874
```

**Comment by cspiby** [comment]
For some reason the debug logger code was removed from my configuration.yaml

Will see what it produces now that is set correctly.

**Comment by cspiby** [comment]
Still the same issue a day later, is there anything else I can do to help narrow down this issue?

`2022-10-31 18:07:54.001 DEBUG (MainThread) [custom_components.octopus_energy.binary_sensor] Updating OctopusEnergyTargetRate washing_machine
2022-10-31 18:07:54.001 DEBUG (MainThread) [custom_components.octopus_energy.binary_sensor] None rate periods found for meter 161000xxxxxxx
2022-10-31 18:07:54.001 DEBUG (MainThread) [custom_components.octopus_energy.target_sensor_utils] Finding rates between 2022-10-31 18:27:54.001751+00:00 and 2022-10-31 21:00:00+00:00
2022-10-31 18:07:54.001 DEBUG (MainThread) [custom_components.octopus_energy.target_sensor_utils] 0 applicable rates found`

**Comment by BottlecapDave** [comment]
hmm odd that your rates are coming back as `None`. I'll try and dig and see why that might be.

**Comment by BottlecapDave** [comment]
I think I've found the issue. I've created a beta release at https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v4.6.5-beta1, which would be great if you could give it a test

**Comment by cspiby** [comment]
That seems to have done the trick, nice work!

**Comment by johnthomas22** [comment]
I still have something like this issue. My automations worked under a previous version. 

Under Developer-> Templates, {{ state_attr('binary_sensor.octopus_energy_target_dishwasher', 'target_times') }} returns a usable set of target times. 

In the automation though, target_times returns an empty sequence. I'm probably missing something daft, but  I can't see it. 

`data:
  message: >-
    Octopus rate is {{ (( (
    states("sensor.octopus_energy_electricity_xxxxxxxxxx_current_rate")|
    float * 100 ) | round(1) )) }}p/kWh.    {%- set target_times =
    state_attr('binary_sensor.octopus_energy_target_dishwasher', 'target_times')
    | map(attribute='start') | sort %}   Best time to run dishwasher is from {{
    target_times }} 

    {# set valid_from_time = target_times | first %}{{
    valid_from_time.strftime("%H:%M") }}  which is {{ (valid_from_time -
    now()).total_seconds() |timestamp_custom('%Hhrs %Mmins') }} from now. #} 
    {%- set overall_average_cost =
    state_attr('binary_sensor.octopus_energy_target_dishwasher','overall_average_cost')
    %} Average price:
    {{state_attr('binary_sensor.octopus_energy_target_dishwasher','overall_average_cost')
    }}p/kWh    Last evaluated: {{
    state_attr('binary_sensor.octopus_energy_target_dishwasher',
    'target_times_last_evaluated') }}
action: notify.notify`

`Executed: 26 December 2024 at 12:01:19
Result:
params:
  domain: notify
  service: notify
  service_data:
    message: |-
      Octopus rate is 23.1p/kWh.   Best time to run dishwasher is from [] 
       Average price: Nonep/kWh    Last evaluated: None
  target: {}
running_script: false`

**Comment by johnthomas22** [comment]
In "Templates" the rates return just fine:

`Octopus rate is 23.1p/kWh.  

Start, end times, rate:(02:30, 03:00, 19.6p);(03:00, 03:30, 19.0p);(03:30, 04:00, 18.3p);(04:00, 04:30, 19.7p);(04:30, 05:00, 19.5p);.

Best time to run dishwasher is from 02:30 which is 15hrs 24mins from now.
Average price: 19.2p/kWh `
