### ISSUE TITLE
Rate tracker fail pull

### ISSUE THREAD

**Issue by rory2409** [BottlecapDave/HomeAssistant-OctopusEnergy#813]
### Describe the bug

It’s all been working flawlessly but the clocks change I think has resulted in no rates being pulled onto the current rate tracker. All other features working

### Reproduction steps

Clock change?

### Expected behaviour

To pull cheapest rates through the day

### Tariff Code

E-1R-AGILE-23-12-06-E

### Integration Version

Latest 

### Home Assistant Version

Latest

### Fresh Install?

Not specified

### Home Assistant Logs

[12_Home_Assistant.log](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/files/14816173/12_Home_Assistant.log)

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Hello and sorry for the late response. Is this still happening? There was an issue with target rate sensors not refreshing in certain scenarios which should be fixed in v10.2.0.

**Comment by rory2409** [comment]
I’m on 10.1.4 and no updates are showing yet I’ll keep you posted once i
receive the update.

**Comment by rory2409** [comment]
Update received seems to be working however it’s an hour out like the other bugs listed

**Comment by BottlecapDave** [comment]
Ok, as this issue is now fixed, I'll close this issue :)

**Comment by rory2409** [comment]
<img width="414" alt="Screenshot 2024-04-07 at 18 01 20 jpeg" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/53194372/18f14b45-c18a-483d-afb5-a6f582abacc1">
<img width="414" alt="Screenshot 2024-04-07 at 18 01 01 jpeg" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/53194372/5468de78-addd-45ef-b6c7-624d4fc2c4e6">


Unfortunately issues remain

**Comment by seanmaskey** [comment]
Hi
I had a similar issue I think; attributes were correct on UTC until 23:00/midnight when they became "unknown". I had set the start & end times in the individual configs to 2300. changing that to 19:00 solved the problem.  wasn't sure if it was coincidental as other things were changing around the same time.
S

**Comment by rory2409** [comment]
I’ve just changed to 1600 and now it is showing on when it should be off as no time matches now time hope this makes sense

**Comment by BottlecapDave** [comment]
@rory2409 I'm not too sure what you're showing here or what you're trying to describe. Please update to v10.2.1 and see if this fixes the issues you're experiencing. 

If it doesn't fix your issue, please supply
* The target times that have picked by the sensor (which are displayed in UTC format)
* A screenshot of the entity in the history tab highlighting when the sensor turns on/off, ideally with annotations of comments on when you feel it should go on/off.

@seanmaskey I believe this was related to https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/815, which was fixed as part of v10.2.1
